apiVersion: nais.io/v1alpha1
kind: Alert
metadata:
  name: sykmeldingalerts
  labels:
    team: teamsykefravr
spec:
  receivers:
    slack:
      channel: '#sykmelding-alerts-dev'
  alerts:
    - alert: syfosm-app-nede
      expr: kube_deployment_status_replicas_available{deployment=~"syfosmregler|syfosmregister|syfotekster|syfohelsenettproxy|syfosmpapirregler|syfosmmanuell-backend|syfosmmanuell|egenmeldt-sykmelding-backend"} == 0
      for: 2m
      description: "{{ $labels.deployment }} er nede"
      action: "Se `kubectl kubectl get pod  | grep {{ $labels.deployment }}` for å se podder, og `kubectl logs $podnavn` for logger"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: syfosm-asynkron-app-nede
      expr: kube_deployment_status_replicas_available{deployment=~"syfosmoppgave|syfosmarena|syfosmvarsel|syfosminfotrygd|syfosmsak|syfosmmottak|syfosmapprec|syfosmpapirmottak|syfovarsel|pale-2|pale-2-sak|helse-sykmelding-router|pale-2-register|egenmeldt-sykmelding-backend"} == 0
      for: 10m
      description: "{{ $labels.deployment }} er nede"
      action: "Se `kubectl kubectl get pod  | grep {{ $labels.deployment }}` for å se podder, og `kubectl logs $podnavn` for logger"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: syfosm-kontinuerlig-restart
      expr: sum(increase(kube_pod_container_status_restarts_total{container=~"syfosmregler|syfosminfotrygd|syfosmregister|syfosmoppgave|syfosmarena|syfosmvarsel|syfosmsak|syfosmmottak|syfosmapprec|syfosmpapirmottak|syfosmpapirregler|syfovarsel|syfosmmanuell-backend|syfosmmanuell|pale-2|pale-2-sak|helse-sykmelding-router|pale-2-register|egenmeldt-sykmelding-backend"}[30m])) by (container) > 2
      for: 5m
      description: "{{ $labels.container }} har restartet flere ganger siste halvtimen!"
      action: "Se `kubectl describe pod {{ $labels.container }}` for events, og `kubectl logs {{ $labels.container }}` for logger"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: syfosm-mangler-metrikker
      expr: absent(up{app=~"syfosmoppgave|syfosmarena|syfosmvarsel|syfosminfotrygd|syfosmregister|syfosmsak|syfosmmottak|syfosmregler|syfohelsenettproxy|syfosmapprec|syfosmpapirmottak|syfosmpapirregler|syfovarsel|syfosmmanuell-backend|pale-2|pale-2-sak|pale-2-register|egenmeldt-sykmelding-backend",job="kubernetes-pods"})
      for: 5m
      description: "{{ $labels.app }} rapporterer ingen metrikker i {{ $labels.kubernetes_namespace }}"
      action: "Sjekk om {{ $labels.app }} i {{ $labels.kubernetes_namespace }} er oppe"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: syfosmmottak-ugyldige-sykmeldinger
      expr: sum(increase(syfosmmottak_invalid_message_no_notice_count[10m])) > 50
      for: 10m
      description: "Syfosmmottak har mottatt unormalt mange ugyldige sykmeldinger"
      action: "Sjekk logger, og om det kan ha blitt innført feil"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: syfosm-error-logging
      expr: sum(rate(logd_messages_total{log_app=~"syfosmoppgave|syfosmarena|syfosmvarsel|syfosminfotrygd|syfosmregister|syfosmsak|syfosmmottak|syfosmregler|syfohelsenettproxy|syfosmapprec|syfosmpapirmottak|syfosmpapirregler|syfosmmanuell-backend|syfosmmanuell|pale-2|pale-2-sak|helse-sykmelding-router|pale-2-register|egenmeldt-sykmelding-backend",log_level="Error",job="kubernetes-pods"}[5m])) by (log_app) > 0
      for: 5m
      description: "{{ $labels.log_app }} rapporterer error i loggene"
      action: "Sjekk hvorfor {{ $labels.log_app }} har i løpet av dei siste 5 minuttene logget Error"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: syfo-errorlogging
      expr: (100 * sum by (log_app) (rate(logd_messages_total{log_app=~"syfovarsel",log_level="Error"}[5m])) / sum by (log_app) (rate(logd_messages_total{log_app=~"syfovarsel"}[5m]))) > 10
      for: 3m
      description: "{{ $labels.log_app }} rapporterer error i loggene"
      action: "Sjekk loggene til {{ $labels.log_app }} for å se hvorfor det er så mye feil"
    - alert: syfosminfotrygd-smikkeokko
      expr: syfosminfotrygd_smikkeok_gauge{log_app=~"syfosminfotrygd"} > 0
      for: 3m
      description: "Meldinger er kommet inn på QA.P414.AS07_SMIKKEOK"
      action: "Sjekk mq køen: QA.P414.AS07_SMIKKEOK, og se på meldinge som har lagt seg der, og kontakt infotrygd teamet, få å finne ut hvorfor den har blitt lagt der"
    - alert: syfovarsel-lytter-stoppet
      expr: sum(increase(syfovarsel_kafkalytter_stoppet_total[30m])) > 10
      for: 10m
      description: "{{ $labels.app }} sin kafkalytter har stoppet"
      action: "Kafkalytter stoppet på syfovarsel. Sjekk logger, og evt. `kubectl delete pod {{ $labels.kubernetes_pod_name }}` for å restarte"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: syfosmregler-avisst-sykmeldinger
      expr: sum(increase(syfosmregler_rule_hit_status_counter{app=~"syfosmregler",rule_status="INVALID"}[30m])) by (rule_status) > 120
      for: 10m
      description: "Syfosmregler har mottatt unormalt mange avisste sykmeldinger"
      action: "Sjekk logger, og om det kan ha blitt innført feil"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: syfosminfotrygd-mange-manuelle-oppg
      expr: (100 * sum(rate(syfosminfotrygd_rule_hit_status_counter{rule_status="MANUAL_PROCESSING"}[10m])) / sum(rate(syfosminfotrygd_rule_hit_status_counter[10m]))) > 200
      for: 10m
      description: "Syfosminfotrygd oppretter unormalt mange oppgaver"
      action: "Sjekk logger, kanskje Infotrygd har problemer"
      sla: respond within 1h, during office hours
      severity: danger
