apiVersion: "nais.io/v1alpha1"
kind: "Alert"
metadata:
  name: sykmeldingalerts
  labels:
    team: teamsykefravr
spec:
  receivers:
    slack:
      channel: '#sykmelding-alerts'
      #prependText: '<!here> | '
  alerts:
    - alert: syfosm-app-nede
      expr: up{app=~"syfosmregler|syfosmregister|syfotekster|syfohelsenettproxy",job="kubernetes-pods"} == 0
      for: 2m
      description: "{{ $labels.app }} er nede i {{ $labels.kubernetes_namespace }}"
      action: "Se `kubectl describe pod {{ $labels.kubernetes_pod_name }}` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }}` for logger"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: syfosm-asynkron-app-nede
      expr: up{app=~"syfosmoppgave|syfosmarena|syfosmvarsel|syfosminfotrygd|syfosmsak|syfosmmottak|syfosmapprec",job="kubernetes-pods"} == 0
      for: 10m
      description: "{{ $labels.app }} er nede i {{ $labels.kubernetes_namespace }}"
      action: "Se `kubectl describe pod {{ $labels.kubernetes_pod_name }}` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }}` for logger"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: syfosm-kontinuerlig-restart
      expr: sum(increase(kube_pod_container_status_restarts_total{container=~"syfosmregler|syfosminfotrygd|syfosmregister|syfosmoppgave|syfosmarena|syfosmvarsel|syfosmsak|syfosmmottak|syfosmapprec"}[30m])) by (container) > 2
      for: 5m
      description: "{{ $labels.container }} har restartet flere ganger siste halvtimen!"
      action: "Se `kubectl describe pod {{ $labels.container }}` for events, og `kubectl logs {{ $labels.container }}` for logger"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: syfosm-mangler-metrikker
      expr: absent(up{app=~"syfosmoppgave|syfosmarena|syfosmvarsel|syfosminfotrygd|syfosmregister|syfosmsak|syfosmmottak|syfosmregler|syfohelsenettproxy|syfosmapprec",job="kubernetes-pods"})
      for: 5m
      description: "{{ $labels.app }} rapporterer ingen metrikker i {{ $labels.kubernetes_namespace }}"
      action: "Sjekk om {{ $labels.app }} i {{ $labels.kubernetes_namespace }} er oppe"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: syfosmmottak-ugyldige-sykmeldinger
      expr: sum(syfosmmottak_invalid_message_no_notice_count) > 100
      for: 10m
      description: "Syfosmmottak har mottatt unormalt mange ugyldige sykmeldinger"
      action: "Sjekk logger, og om det kan ha blitt innført feil"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: syfosm-error-logging
      expr: sum(rate(logd_messages_total{log_app=~"syfosmoppgave|syfosmarena|syfosmvarsel|syfosminfotrygd|syfosmregister|syfosmsak|syfosmmottak|syfosmregler|syfohelsenettproxy|syfosmapprec",log_level="Error",job="kubernetes-pods"}[5m])) by (log_app) > 0
      for: 5m
      description: "{{ $labels.log_app }} rapporterer error i loggene"
      action: "Sjekk hvorfor {{ $labels.log_app }} har i løpet av dei siste 5 minuttene logget Error"
      sla: respond within 1h, during office hours
      severity: danger
    - alert: syfosminfotrygd-smikkeokko
      expr: syfosminfotrygd_smikkeok_gauge{log_app=~"syfosminfotrygd"} > 0
      for: 3m
      description: "Meldinger er kommet inn på QA.P414.AS07_SMIKKEOK"
      action: "Sjekk mq køen: QA.P414.AS07_SMIKKEOK, og se på meldinge som har lagt seg der, og kontakt infotrygd teamet, få å finne ut hvorfor den har blitt lagt der"
