name: Deploy to dev and prod
on:
  push:
    branches:
      - master
jobs:
  deploy_prod:
    name: Deploy alert til prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Call deployment-cli/action and apply yaml file to dev-fss
        uses: navikt/deployment-cli/action@0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cluster: dev-fss
          team: teamsykefravr
          rawresources: sykmeldingalerts-dev.yaml
      - name: Call deployment-cli/action and apply yaml file to prod-fss
        uses: navikt/deployment-cli/action@0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cluster: prod-fss
          team: teamsykefravr
          rawresources: sykmeldingalerts-prod.yaml