name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy_prod:
    name: deploy prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: deploy to prod
        uses: nais/deploy@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cluster: prod-fss
          repository: navikt/sykmelding-alerts
          team: teamsykefravr
          resource: sykmeldingalerts.yaml