name: Deploy to NAIS
on:
  push:
    branches:
      - master
jobs:
  deploy_prod:
    name: deploy prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: deploy to prod-fss
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | docker run -v $GITHUB_WORKSPACE:/workspace navikt/deployment-cli deployment-cli deploy create \
            --cluster=dev-fss \
            --repository=navikt/sykmelding-alerts \
            --team=teamsykefravr \
            --resource=/workspace/sykmeldingalerts.yaml \
            --token=${GITHUB_TOKEN}