name: Deploy to dev and prod
on:
  push:
    branches:
      - master
jobs:
  deploy_prod:
    name: Deploy alert til prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Deploy to dev
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: sykmeldingalerts-dev.yaml
      - name: Deploy to prod
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: sykmeldingalerts-prod.yaml
