name: Deploy sykmelding alert to NAIS
on:
  push:
    branches:
      - master
jobs:
  deploy_prod:
    name: Deploy alert til prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Call deployment-cli and apply yaml file to prod-fss
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker run -v $GITHUB_WORKSPACE:/workspace navikt/deployment-cli deployment-cli deploy create \
            --cluster=prod-fss \
            --repository=navikt/sykmelding-alerts \
            --team=teamsykefravr \
            --no-template-resource=/workspace/sykmeldingalerts.yaml \
            --token=${GITHUB_TOKEN}